### PR TITLE
UIA-8022 - Changing domain police to allow 'www.' with any url hostname

### PR DESCRIPTION
**Pull request by mgoodnow**
…ut the need to explicitly define

### CODE REVIEW

**Comment by sirugh** [comment]
Please update or add [unit tests](https://github.com/mgoodnow/bv-ui-core/blob/master/test/unit/domainPolice/index.spec.js).

**Comment by mgoodnow** [comment]
Unit tests updated

**Comment by sirugh** [comment]
Failing due to phantomjs rate limit....

**Comment by aterranova-bv** [comment]
Is it useful to be able to set your preferred policy (all sub-domains, or not) when constructing a domain police object?

In other words, this change is going to alter functionality for existing users. Should we provide something for backwards compatibility?

**Comment by reason-bv** [comment]
Allowing subdomains by default is a security threat in the abstract. Consider the issues that GitHub had with that, for example. It isn't necessarily the case that a company would want by default all subdomains to be allowable.

**Comment by mgoodnow** [comment]
@reason-bv not sure I'm familiar with the security concerns you are raising, but I'll trust your judgement. Currently confighub does not store invalid domain (due to them being used for other purposes), thus allowing user to enter in `.domain.com` would be considered invalid. One potential option we could do is how we handle `allowThirdParty` in that we have a checkbox for `allowSubDomains`. I'll run this by Patrick T. Thanks for your feedback.

**Comment by sirugh** [comment]
https://github.com/blog/1452-new-github-pages-domain-github-io

**Comment by mgoodnow** [comment]
@reason-bv and @aterranova-bv Please review latest comment in https://bits.bazaarvoice.com/jira/browse/CCS-6339 for potential aternative measures at solving the problem at hand. Thanks.

**Comment by mgoodnow** [comment]
Updated PR to include allowing `www.` along with any hostname.

**Comment by taylormck** [comment]
I'm 👍  with these changes.
I'd still like to ping @reason-bv for a final look before merging.

**Comment by reason-bv** [comment]
I'm good with this.

**Pull request merged**
